{
 "title": "Stream Replicator",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "replicator",
    "label": "Replicator",
    "query": {
     "query": "label_values(choria_stream_replicator_replicator_total_messages, replicator)"
    }
   },
   {
    "name": "stream",
    "query": {
     "query": "label_values(choria_stream_replicator_replicator_total_messages, stream)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Replication Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Messages / 5 Minutes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(choria_stream_replicator_replicator_total_messages{replicator=~\"${replicator}\",stream=~\"${stream}\"}[5m])",
     "legendFormat": "Total Messages"
    },
    {
     "expr": "increase(choria_stream_replicator_replicator_total_messages{replicator=~\"${replicator}\",stream=~\"${stream}\"}[5m])\n-\nincrease(choria_stream_replicator_replicator_skipped_messages{replicator=~\"${replicator}\",stream=~\"${stream}\"}[5m])",
     "legendFormat": "Copied Messages"
    },
    {
     "expr": "choria_stream_replicator_replicator_stream_lag_messages{replicator=~\"${replicator}\",stream=~\"${stream}\"}",
     "legendFormat": "Lag"
    }
   ]
  },
  {
   "title": "Bytes / 5 Minutes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "increase(choria_stream_replicator_replicator_total_bytes{replicator=~\"${replicator}\",stream=~\"${stream}\"}[5m])",
     "legendFormat": "Total Bytes"
    },
    {
     "expr": "increase(choria_stream_replicator_replicator_total_bytes{replicator=~\"${replicator}\",stream=~\"${stream}\"}[5m])\n-\nincrease(choria_stream_replicator_replicator_skipped_bytes{replicator=~\"${replicator}\",stream=~\"${stream}\"}[5m])",
     "legendFormat": "Copied Bytes"
    }
   ]
  },
  {
   "title": "Sampling %",
   "type": "gauge",
   "description": "Indicates the effectiveness of the sampling configuration, a value of 80 means 80/100 messages received from the source was not copied to the targets",
   "gridPos": { "h": 8, "w": 4, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(choria_stream_replicator_replicator_skipped_messages{replicator=~\"${replicator}\",stream=~\"${stream}\"}[5m])\n/\nrate(choria_stream_replicator_replicator_total_messages{replicator=~\"${replicator}\",stream=~\"${stream}\"}[5m])\n*\n100"
    }
   ]
  },
  {
   "title": "Replicated / 5 min",
   "type": "stat",
   "description": "Messages copied to the target, if limits are applied this would be a fraction of total",
   "gridPos": { "h": 8, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(choria_stream_replicator_replicator_total_messages{replicator=~\"${replicator}\",stream=~\"${stream}\"}[5m])\n-\nincrease(choria_stream_replicator_replicator_skipped_messages{replicator=~\"${replicator}\",stream=~\"${stream}\"}[5m]))"
    }
   ]
  },
  {
   "title": "Replicated Bytes / sec",
   "type": "stat",
   "description": "Bytes copied to the target subject to sampling by the limiter configuration",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(choria_stream_replicator_replicator_total_bytes{replicator=~\"${replicator}\",stream=~\"${stream}\"}[5m])\n-\nrate(choria_stream_replicator_replicator_skipped_bytes{replicator=~\"${replicator}\",stream=~\"${stream}\"}[5m]))"
    }
   ]
  },
  {
   "title": "Advisories / 5 Minutes",
   "type": "timeseries",
   "description": "Advisories issued by the limiter",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(choria_stream_replicator_advisor_total_messages{replicator=~\"${replicator}\",stream=~\"${stream}\"}[5m])) by (advisory)",
     "legendFormat": " {{advisory}}"
    }
   ]
  },
  {
   "title": "Message Processing Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(choria_stream_replicator_replicator_processing_time_seconds_sum{replicator=\"${replicator}\",stream=~\"${stream}\"}[5m])\n/\nrate(choria_stream_replicator_replicator_processing_time_seconds_count{replicator=\"${replicator}\",stream=~\"${stream}\"}[5m])) by (replicator)",
     "legendFormat": "{{replicator}}"
    }
   ]
  },
  {
   "title": "Tracked Items",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 14, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "choria_stream_replicator_tracker_total_items{replicator=~\"${replicator}\",stream=~\"${stream}\"}"
    }
   ]
  },
  {
   "title": "Processed / 5 min",
   "type": "stat",
   "description": "Total number of messages received from the Source",
   "gridPos": { "h": 8, "w": 3, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(choria_stream_replicator_replicator_total_messages{replicator=~\"${replicator}\",stream=~\"${stream}\"}[5m]))"
    }
   ]
  },
  {
   "title": "Processed Bytes / sec",
   "type": "stat",
   "description": "Total bytes received from the Source",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(choria_stream_replicator_replicator_total_bytes{replicator=~\"${replicator}\",stream=~\"${stream}\"}[5m]))"
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Handler Errors",
   "type": "timeseries",
   "description": "Times handling a single message failed",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(choria_stream_replicator_replicator_handler_error_count[5m])",
     "legendFormat": "{{replicator}} - {{stream}} handler"
    },
    {
     "expr": "increase(choria_stream_replicator_replicator_ack_failed_count[5m])",
     "legendFormat": "{{replicator}} - {{stream}} ack"
    }
   ]
  },
  {
   "title": "Metadata Parse Errors",
   "type": "timeseries",
   "description": "Times parsing metadata about a JetStream message failed",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(choria_stream_replicator_replicator_meta_parse_failed_count[5m])",
     "legendFormat": "{{replicator}} - {{stream}}"
    }
   ]
  },
  {
   "title": "Consumer Recreated",
   "type": "timeseries",
   "description": "Times the durable consumer in the Source stream had to be recreated",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(choria_stream_replicator_replicator_consumer_recreated[5m])",
     "legendFormat": "{{replicator}} - {{stream}}"
    }
   ]
  },
  {
   "title": "Advisory Errors",
   "type": "timeseries",
   "description": "Times an advisory could not be published",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(choria_stream_replicator_advisor_publish_errors[5m])",
     "legendFormat": "{{replicator}} - {{stream}}"
    }
   ]
  }
 ]
}